FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y \
    bluetooth bluez libbluetooth-dev \
    libglib2.0-dev libdbus-1-dev \
    libcairo2-dev libgirepository1.0-dev \
    pkg-config \
    gcc python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app
COPY pyproject.toml .
RUN uv pip install --system --no-cache -e .[iot]

COPY pi/python/code.py .

CMD ["python3", "code.py"]
