#!/bin/bash

# LED control script
# GPIO17 = Green LED (1017)
# GPIO27 = Red LED (1027)

GREEN_PIN=17
RED_PIN=27

case "$1" in
    green)
        if [ "$2" = "0" ]; then
            gpioset gpiochip0 $GREEN_PIN=0
            echo "Green LED OFF"
        else
            gpioset gpiochip0 $GREEN_PIN=1
            echo "Green LED ON"
        fi
        ;;
    red)
        if [ "$2" = "0" ]; then
            gpioset gpiochip0 $RED_PIN=0
            echo "Red LED OFF"
        else
            gpioset gpiochip0 $RED_PIN=1
            echo "Red LED ON"
        fi
        ;;
    all)
        if [ "$2" = "0" ]; then
            gpioset gpiochip0 $GREEN_PIN=0 $RED_PIN=0
            echo "All LEDs OFF"
        else
            gpioset gpiochip0 $GREEN_PIN=1 $RED_PIN=1
            echo "All LEDs ON"
        fi
        ;;
    *)
        echo "Usage: led {green|red|all} {0|1}"
        echo "  led green 1  - Turn green LED ON"
        echo "  led green 0  - Turn green LED OFF"
        echo "  led red 1    - Turn red LED ON"
        echo "  led red 0    - Turn red LED OFF"
        echo "  led all 1    - Turn all LEDs ON"
        echo "  led all 0    - Turn all LEDs OFF"
        exit 1
        ;;
esac
